<?php
include("../config/db.php");

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header("Location: ../login.php");
    exit();
}

// Get parameters
$from_date = isset($_GET['from']) ? $_GET['from'] : date('Y-m-01');
$to_date = isset($_GET['to']) ? $_GET['to'] : date('Y-m-d');
$report_type = isset($_GET['type']) ? $_GET['type'] : 'sales';

// Set headers for Excel download
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="' . $report_type . '_report_' . date('Y-m-d') . '.xls"');
header('Pragma: no-cache');
header('Expires: 0');

// Start HTML table for Excel
echo '<html xmlns:x="urn:schemas-microsoft-com:office:excel">';
echo '<head>';
echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />';
echo '<style>';
echo 'table { border-collapse: collapse; width: 100%; }';
echo 'th, td { border: 1px solid #000; padding: 8px; text-align: left; }';
echo 'th { background-color: #4CAF50; color: white; font-weight: bold; }';
echo '.total-row { background-color: #f3f4f6; font-weight: bold; }';
echo '</style>';
echo '</head>';
echo '<body>';

// Report Header
echo '<h2>Pharmacy Management System</h2>';
echo '<h3>' . ucfirst($report_type) . ' Report</h3>';
echo '<p><strong>Period:</strong> ' . date('d M Y', strtotime($from_date)) . ' to ' . date('d M Y', strtotime($to_date)) . '</p>';
echo '<p><strong>Generated:</strong> ' . date('d M Y, h:i A') . '</p>';
echo '<p><strong>Generated By:</strong> ' . $_SESSION['full_name'] . '</p>';
echo '<br>';

if ($report_type == 'sales') {
    // Sales Report
    $sales_report = mysqli_query($conn, "SELECT DATE(sale_date) as date, COUNT(*) as total_sales, 
        SUM(grand_total) as revenue, SUM(tax_amount) as total_tax, SUM(discount_amount) as total_discount 
        FROM sales WHERE DATE(sale_date) BETWEEN '$from_date' AND '$to_date' 
        GROUP BY DATE(sale_date) ORDER BY date DESC");
    
    echo '<table>';
    echo '<thead>';
    echo '<tr>';
    echo '<th>Date</th>';
    echo '<th>Total Sales</th>';
    echo '<th>Revenue (Rs)</th>';
    echo '<th>Tax (Rs)</th>';
    echo '<th>Discount (Rs)</th>';
    echo '<th>Net Revenue (Rs)</th>';
    echo '</tr>';
    echo '</thead>';
    echo '<tbody>';
    
    $total_revenue_sum = 0;
    $total_sales_count = 0;
    $total_tax_sum = 0;
    $total_discount_sum = 0;
    
    while ($report = mysqli_fetch_assoc($sales_report)) {
        $total_revenue_sum += $report['revenue'];
        $total_sales_count += $report['total_sales'];
        $total_tax_sum += $report['total_tax'];
        $total_discount_sum += $report['total_discount'];
        
        echo '<tr>';
        echo '<td>' . date('d M Y', strtotime($report['date'])) . '</td>';
        echo '<td>' . $report['total_sales'] . '</td>';
        echo '<td>' . number_format($report['revenue'], 2) . '</td>';
        echo '<td>' . number_format($report['total_tax'], 2) . '</td>';
        echo '<td>' . number_format($report['total_discount'], 2) . '</td>';
        echo '<td>' . number_format($report['revenue'] - $report['total_discount'], 2) . '</td>';
        echo '</tr>';
    }
    
    echo '<tr class="total-row">';
    echo '<td><strong>TOTAL</strong></td>';
    echo '<td><strong>' . $total_sales_count . '</strong></td>';
    echo '<td><strong>' . number_format($total_revenue_sum, 2) . '</strong></td>';
    echo '<td><strong>' . number_format($total_tax_sum, 2) . '</strong></td>';
    echo '<td><strong>' . number_format($total_discount_sum, 2) . '</strong></td>';
    echo '<td><strong>' . number_format($total_revenue_sum - $total_discount_sum, 2) . '</strong></td>';
    echo '</tr>';
    
    echo '</tbody>';
    echo '</table>';
    
} elseif ($report_type == 'medicines') {
    // Top Medicines Report
    $top_medicines = mysqli_query($conn, "SELECT m.medicine_name, m.generic_name, c.company_name,
        SUM(si.quantity) as total_sold, SUM(si.subtotal) as total_revenue,
        COUNT(DISTINCT si.sale_id) as times_sold
        FROM sale_items si 
        JOIN medicines m ON si.medicine_id = m.id 
        LEFT JOIN companies c ON m.company_id = c.id
        JOIN sales s ON si.sale_id = s.id 
        WHERE DATE(s.sale_date) BETWEEN '$from_date' AND '$to_date'
        GROUP BY si.medicine_id 
        ORDER BY total_sold DESC 
        LIMIT 50");
    
    echo '<table>';
    echo '<thead>';
    echo '<tr>';
    echo '<th>#</th>';
    echo '<th>Medicine Name</th>';
    echo '<th>Generic Name</th>';
    echo '<th>Company</th>';
    echo '<th>Units Sold</th>';
    echo '<th>Times Ordered</th>';
    echo '<th>Total Revenue (Rs)</th>';
    echo '</tr>';
    echo '</thead>';
    echo '<tbody>';
    
    $i = 1;
    $total_units = 0;
    $total_revenue = 0;
    
    while ($med = mysqli_fetch_assoc($top_medicines)) {
        $total_units += $med['total_sold'];
        $total_revenue += $med['total_revenue'];
        
        echo '<tr>';
        echo '<td>' . $i++ . '</td>';
        echo '<td>' . $med['medicine_name'] . '</td>';
        echo '<td>' . $med['generic_name'] . '</td>';
        echo '<td>' . $med['company_name'] . '</td>';
        echo '<td>' . $med['total_sold'] . '</td>';
        echo '<td>' . $med['times_sold'] . '</td>';
        echo '<td>' . number_format($med['total_revenue'], 2) . '</td>';
        echo '</tr>';
    }
    
    echo '<tr class="total-row">';
    echo '<td colspan="4"><strong>TOTAL</strong></td>';
    echo '<td><strong>' . $total_units . '</strong></td>';
    echo '<td><strong>-</strong></td>';
    echo '<td><strong>' . number_format($total_revenue, 2) . '</strong></td>';
    echo '</tr>';
    
    echo '</tbody>';
    echo '</table>';
    
} elseif ($report_type == 'purchases') {
    // Purchase Report
    $purchase_report = mysqli_query($conn, "SELECT DATE(p.purchase_date) as date, 
        COUNT(*) as total_purchases, SUM(p.grand_total) as total_amount, s.supplier_name
        FROM purchases p
        LEFT JOIN suppliers s ON p.supplier_id = s.id
        WHERE DATE(p.purchase_date) BETWEEN '$from_date' AND '$to_date'
        GROUP BY DATE(p.purchase_date)
        ORDER BY date DESC");
    
    echo '<table>';
    echo '<thead>';
    echo '<tr>';
    echo '<th>Date</th>';
    echo '<th>Supplier</th>';
    echo '<th>Total Purchases</th>';
    echo '<th>Total Amount (Rs)</th>';
    echo '</tr>';
    echo '</thead>';
    echo '<tbody>';
    
    $total_purchase_amount = 0;
    $total_purchase_count = 0;
    
    while ($purchase = mysqli_fetch_assoc($purchase_report)) {
        $total_purchase_amount += $purchase['total_amount'];
        $total_purchase_count += $purchase['total_purchases'];
        
        echo '<tr>';
        echo '<td>' . date('d M Y', strtotime($purchase['date'])) . '</td>';
        echo '<td>' . ($purchase['supplier_name'] ?? 'N/A') . '</td>';
        echo '<td>' . $purchase['total_purchases'] . '</td>';
        echo '<td>' . number_format($purchase['total_amount'], 2) . '</td>';
        echo '</tr>';
    }
    
    echo '<tr class="total-row">';
    echo '<td colspan="2"><strong>TOTAL</strong></td>';
    echo '<td><strong>' . $total_purchase_count . '</strong></td>';
    echo '<td><strong>' . number_format($total_purchase_amount, 2) . '</strong></td>';
    echo '</tr>';
    
    echo '</tbody>';
    echo '</table>';
    
} elseif ($report_type == 'customers') {
    // Customer Report
    $customer_report = mysqli_query($conn, "SELECT c.customer_name, c.phone,
        COUNT(s.id) as total_orders, SUM(s.grand_total) as total_spent
        FROM customers c
        JOIN sales s ON c.id = s.customer_id
        WHERE DATE(s.sale_date) BETWEEN '$from_date' AND '$to_date'
        GROUP BY c.id
        ORDER BY total_spent DESC
        LIMIT 50");
    
    echo '<table>';
    echo '<thead>';
    echo '<tr>';
    echo '<th>#</th>';
    echo '<th>Customer Name</th>';
    echo '<th>Phone</th>';
    echo '<th>Total Orders</th>';
    echo '<th>Total Spent (Rs)</th>';
    echo '<th>Avg Order Value (Rs)</th>';
    echo '</tr>';
    echo '</thead>';
    echo '<tbody>';
    
    $i = 1;
    $total_orders = 0;
    $total_spent = 0;
    
    while ($customer = mysqli_fetch_assoc($customer_report)) {
        $avg_order = $customer['total_spent'] / $customer['total_orders'];
        $total_orders += $customer['total_orders'];
        $total_spent += $customer['total_spent'];
        
        echo '<tr>';
        echo '<td>' . $i++ . '</td>';
        echo '<td>' . $customer['customer_name'] . '</td>';
        echo '<td>' . $customer['phone'] . '</td>';
        echo '<td>' . $customer['total_orders'] . '</td>';
        echo '<td>' . number_format($customer['total_spent'], 2) . '</td>';
        echo '<td>' . number_format($avg_order, 2) . '</td>';
        echo '</tr>';
    }
    
    echo '<tr class="total-row">';
    echo '<td colspan="3"><strong>TOTAL</strong></td>';
    echo '<td><strong>' . $total_orders . '</strong></td>';
    echo '<td><strong>' . number_format($total_spent, 2) . '</strong></td>';
    echo '<td><strong>-</strong></td>';
    echo '</tr>';
    
    echo '</tbody>';
    echo '</table>';
}

// Footer
echo '<br><br>';
echo '<p><em>This is a computer-generated report from Pharmacy Management System</em></p>';
echo '<p><em>Generated on: ' . date('d M Y, h:i:s A') . '</em></p>';

echo '</body>';
echo '</html>';
?>
